Mail chimp
VilllageBookBuilders/VBBPortal pull request #103
Opened 2020-10-04 19:29 UTC by Aleksei-Zaichenko

Loom video: https://www.loom.com/share/de2b093a3be140bfaac715badc88b8bd

Modified Step1.js in MasterForm.js. I added validation for each input field, introduced a new field (country code) and if a new user chooses "yes" for sign up for newsletter field, this form makes a post request to back-end api and then to MailChimp api. 

Created a new rest api endpoint to accept a new user`s credentials and then send them to MailChimp api.

2020-10-05 14:18 UTC, brighamband commented
Looks great! Good work!
I'd approve it, but it says merging is blocked

2020-10-05 20:38 UTC, edringger requested changes
Looks great! The only thing I would change would be to make country code somehow be on the same line as phone number. Right now it's not very intuitive. Most people are comfortable typing in their country code as part of their phone number anyways, I think. I would just remove that part of the form for now, and add it as a separate issue to work on later, since the mail chimp part works. 

Using something like this would be cool: npmjs.com/package/react-phone-input-2

2020-10-05 20:38 UTC, edringger commented on api/urls.py
> +    path("signup/subscriptionForNewsletters/",sign_up_for_newsletters ),
you can probably just make this its own url path outright (ie /subscribe) but I guess it doesn't really meatter

2020-10-05 20:38 UTC, edringger commented on src/components/registration/Step1.js
> +
I think this should be combined with the phone field. It's not very intuitive to have to put your country code in a separate box, and most people know to put their country code in with their phone number

2020-10-07 21:40 UTC, edringger approved these changes

2020-10-07 21:40 UTC, merged